;; -*- mode: eask; lexical-binding: t -*-

(package "impatient-mode"
         "1.1"
         "Serve buffers live over HTTP")

(website-url "https://github.com/skeeto/impatient-mode")
(keywords "")

(package-file "impatient-mode.el")
(files "README.md" "loading.html" "jquery.js" "index.html")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "27.1")
(depends-on "simple-httpd")
(depends-on "htmlize")
